blog/urls.py
from django.urls import path
from blog.views import *

app_name ='blog'

urlpatterns = [
    path('',blog_views,name='index'),
    # path('single' ,blog_single,name='single'),
    path('<int:pid>' ,blog_single,name='single'),
    path('category/<str:cat_name>',blog_views,name='category'),
    path('tag/<str:tag_name>',blog_views,name='tag'),
    path('author/<str:author_username>',blog_views,name='author'),
    path('search/',blog_search,name='search'),
    path('newsletter/',newsletter_view,name='newsletter'),
]

my_site/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
import debug_toolbar

sitemaps ={
    'static':StaticViewSitemap,
    'blog' :BlogSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('website.urls')),
    path('blog/',include('blog.urls')),


    path ('sitemap.xml', sitemap ,{'sitemaps':sitemaps},
            name ='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt',include('robots.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
    path('summernote/', include('django_summernote.urls')),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [ path('captcha/', include('captcha.urls')), ]

website/urls.py
from django.urls import path
from website.views import *

app_name ='website'

urlpatterns = [
    path('',index_views,name='index'),
    path('contact',contact_view,name='contact'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

# Create your models here.
class category (models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name
class post (models.Model):
    image = models.ImageField(upload_to='blog/',default='blog/default.jpg')
    author = models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    title =models.CharField(max_length= 255)
    content = models.TextField()
    tags = TaggableManager()
    category =models.ManyToManyField(category)
    counted_views = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    published_date = models.DateTimeField(null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    class Meta:
        ordering = ['-created_date']

    def __str__(self) :
        return "{} - {}" .format(self.title,self.id) 

    def get_absolute_url (self):
        return reverse('blog:single',kwargs={'pid':self.id})

class Newsletter(models.Model):
    email =models.EmailField()
    def __str__(self) :
        return self.email

website/models.py
from django.db import models

# Create your models here.
class contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True )
    class Meta:
        ordering = ['-created_date']

blog/forms.py
from django import forms
from blog.models import Newsletter
from captcha.fields import CaptchaField

class NewsletterForm(forms.ModelForm):
    class Meta:
        model = Newsletter
        fields = '__all__'

website/forms.py
from django import forms
from website.models import contact
from captcha.fields import CaptchaField

class NameForm(forms.Form):
    name = forms.CharField(max_length=255)
    email =forms.EmailField()
    subject =forms.CharField(max_length=255)
    message = forms.CharField(widget=forms.Textarea)
    


class ContactForm (forms.ModelForm):
    class Meta:
        model =contact
        fields = '__all__'    

blog/views.py
from django.shortcuts import render,get_object_or_404
from blog.models import post 
from django.http import HttpResponseRedirect,HttpResponse
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from blog.forms import NewsletterForm
# Create your views here.
def blog_views(request,**kwargs):
    posts = post.objects.filter(status=1)
    if kwargs.get  ('cat_name')!=None:
        posts=posts.filter(category__name=kwargs['cat_name'])
    if kwargs.get  ('author_username')!=None:
       posts=posts.filter(author__username=kwargs['author_username']) 
    if kwargs.get  ('tag_name')!=None:
       posts=posts.filter(tags__name__in=[kwargs['tag_name']])
    posts=Paginator(posts,3)

    try:
        page_number = request.GET.get('page')
        posts =posts.get_page(page_number)
    except PageNotAnInteger :
        posts =posts.get_page(1)
    except EmptyPage:
        posts =posts.get_page(1)
    context={'posts':posts}
    return render(request,'blog/portfolio_details.html',context)



def blog_single(request,pid=6):
    posts = get_object_or_404(post,pk=pid)
    context={'posts':posts}
    return render(request,'blog/single.html',context)


def blog_search(request):
    posts = post.objects.filter(status=1)
    if request.method == 'GET' :
        posts=posts.filter(content__contains=request.GET.get('s'))
    context={'posts':posts}
    return render(request,'blog/portfolio_details.html',context)

def newsletter_view (request):
    if request.method == 'POST':
        form =NewsletterForm(request.POST)
        if form.is_valid():
            form.save()
        return HttpResponseRedirect('/blog')
    else:
        return HttpResponseRedirect('/blog')

website/views.py
from django.shortcuts import render
from django.http import HttpResponse,JsonResponse
from website.models import contact
from website.forms import NameForm , ContactForm
from django.contrib import messages
from django.http import HttpResponseRedirect
# Create your views here.
def index_views(request):
    return render(request,'website/index.html')

def portfolio_details_views(request):
    return render(request,'blog/portfolio_details.html')

def contact_view(request):
    if request.method == 'POST':
        form =ContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Your message has been sent. Thank you! :)')
            return HttpResponseRedirect('/#contact')
        else:
            messages.add_message(request, messages.WARNING, 'Your message was not sent')
            return HttpResponseRedirect('/#contact')
        
    else:
        form = ContactForm()
    return render(request, 'website/index.html',{'form':form})

templates/blog/Widget.html
{% load static %}
<div id="Widget">
  <p id="titel">view</p>
  <div id="n">
    <ul>
      <li>Today:<span data-purecounter-start="0" data-purecounter-end="8" data-purecounter-duration="1"
          class="purecounter"></span></li>
      <li>Month:<span data-purecounter-start="0" data-purecounter-end="255" data-purecounter-duration="1"
          class="purecounter"></span></li>
      <li>total:<span data-purecounter-start="0" data-purecounter-end="255" data-purecounter-duration="1"
          class="purecounter"></span></li>
    </ul>
  </div>
</div>

templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>blog</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static '/img/favicon.png '%}" rel="icon">
  <link href="{% static '/img/apple-touch-icon.png '%}" rel="apple-touch-icon">

  <!-- back gerund -->
  <img id="bg" src="{%static '/img/bg.jpg'%}" alt="">
  <!-- Something -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.6.1.min.js"
    integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

  <!-- Vendor CSS Files -->
  <link href="{% static '/vendor/bootstrap/css/bootstrap.min.css '%}" rel="stylesheet">
  <link href="{% static '/vendor/bootstrap-icons/bootstrap-icons.css '%}" rel="stylesheet">
  <link href="{% static '/vendor/boxicons/css/boxicons.min.css '%}" rel="stylesheet">
  <link href="{% static '/vendor/glightbox/css/glightbox.min.css '%}" rel="stylesheet">
  <link href="{% static '/vendor/remixicon/remixicon.css '%}" rel="stylesheet">
  <link href="{% static '/vendor/swiper/swiper-bundle.min.css '%}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static '/css/css.css '%}" rel="stylesheet">

  <!-- ============================================================================== -->
  <!-- navbar -->

  <nav class="navbar navbar-expand-lg bg-dark fixed-top fs-5 " style="height:1cm;  ">
    <div class="container-fluid fs-5 " style="height:1cm;  ">
      <button class="navbar-toggler fs-5 " type="button" data-bs-toggle="collapse"
        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
        aria-label="Toggle navigation" style="height:1cm;  ">
        <span class="navbar-toggler-icon fs-5 " style="height:1cm;  "></span>
      </button>
      <div class="collapse navbar-collapse fs-5 " id="navbarSupportedContent" style="height:1cm;  ">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item" style="height:1cm;  ">
            <a class="nav-link active fs-5 " style="height:1cm;  " aria-current="page"
              href="{%url 'website:index'%}">Home</a>
          </li>

          <li class="nav-item dropdownfs-5 " style="height:1cm;  ">
            <a class="nav-link dropdown-toggle fs-5 " href="#" role="button" data-bs-toggle="dropdown"
              aria-expanded="false" style="height:1cm;  ">
              Dropdown
            </a>
            <ul class="dropdown-menu" style="height:1cm;  ">
              <li><a class="dropdown-item fs-4" style="height:1cm;  " href="#">About</a></li>
              <li><a class="dropdown-item fs-4" style="height:1cm;  " href="#">Another action</a></li>
              <li><a class="dropdown-item fs-4" style="height:1cm;  " href="#">Something else here</a></li>
            </ul>
          </li>
        </ul>
        <form class="d-flex" role="search" action="{% url 'blog:search' %}" method="get" style="height:1cm;  ">
          <input class="form-control me-2 fs-5 " type="search" placeholder="Search" name="s" aria-label="Search"
            style="height:1cm;  ">
          <button class="btn btn-outline-success fs-5 " type="submit" style="height:1cm;  ">Search</button>
        </form>
      </div>
    </div>
  </nav>
  <!-- end navbar -->
</head>

<body>
  {% block content %}


  {% endblock %}
  <div class="footer ">
    <div>
      <p>+989156557328 <span class="glyphicon glyphicon-earphone"></span></p>
      <p>mahdi.yazdanpanah000@gmail.com <span class="glyphicon glyphicon-globe"></span></p>
    </div>

    <form action="{% url 'blog:newsletter' %}" method="post" class="co ">
      <div class="mb-3">
        {% csrf_token %}
        <label for="exampleFormControlInput1" class="form-label">newsletter</label>
        <input name="email" type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
      </div>
      <div class="pb-3">
      {{form.captcha}}
    </div>
      <button class="btn btn-success"  type="submit"  >send</button>

      <div class="toast-container position-fixed bottom-0 end-0 p-3">
        <div id="liveToast" class="toast" role="alert" aria-live="assertive" aria-atomic="true">
          <div class="toast-header">
            <img src="{% static '/img/favicon.png '%}" class="rounded me-2" alt="...">
            <strong class="me-auto">mahdi yazdanpanah</strong>
            <small>just now</small>
            <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
          </div>
          <div class="toast-body">
            Hello, your email has been sent successfully
          </div>
        </div>
      </div>
    </form>
  </div>
  </div>

  <!-- Vendor JS Files -->
  <script src="{% static '/vendor/purecounter/purecounter_vanilla.js '%}"></script>
  <script src="{% static '/vendor/bootstrap/js/bootstrap.bundle.min.js '%}"></script>
  <script src="{% static '/vendor/glightbox/js/glightbox.min.js '%}"></script>
  <script src="{% static '/vendor/isotope-layout/isotope.pkgd.min.js '%}"></script>
  <script src="{% static '/vendor/swiper/swiper-bundle.min.js '%}"></script>
  <script src="{% static '/vendor/waypoints/noframework.waypoints.js '%}"></script>
  <script src="{% static '/vendor/php-email-form/validate.js '%}"></script>

  <!-- Template Main JS File -->
  <script src="{% static '/js/main.js '%}"></script>

</body>
<script>
  $(document).ready(function () {
    $('#liveToastBtn').click(function () {
      $('#liveToast').toast({ delay: 10000 })
      $('#liveToast').toast('show')
    });
  });
</script>

</html>

templates/blog/pd1.html
{% extends './base.html' %}
{% load static %}
{% load blog_tags %}
{% block content %}

<body>

  <!-- ======= Portfolio Details ======= -->
  <main id="main">
    <div>
      <div id="details">
        <div id="w">
          {% include 'blog/Widget.html' %}
          {% include 'blog/Widget1.html' %}
          {% include 'blog/Widget2.html' %}
          {% include 'blog/Widget3.html' %}
        </div>
        <div class="container">
          <h1 id="title">blog detail</h1>

          {% for post in posts %}
          <div class="post container">
            <div class="media">
              <img width="100%" src="{{post.image.url}}" alt="">
            </div>
            <div class="title">
              <a href="{% url 'blog:single' pid=post.id %}"><h1>{{post.title}}</h1></a>
            </div>
            <div class="parent">
              <div class="info">
                <p>{{post.author.get_full_name}} <span class="glyphicon glyphicon-user"></span></p>
                <p>{{post.published_date | date:" D d M Y"}} <span class="glyphicon glyphicon-calendar"></span></p>
                <p>{{post.counted_views}} view <span class="glyphicon glyphicon-eye-open"></span></p>
                <p>
                  {% for cat in post.category.all %}
                  <a href="#">{{cat}}</a>{% if not forloop.last %},{% endif %}
                  {% endfor %}
                </p>
              </div>

              <div class="content">
                <p>{{post.content|truncatechars:150}}</p>
                <a href="{% url 'blog:single' pid=post.id %}" class="btn btn-Success active" aria-current="page">more</a>

              </div>
            </div>

          </div>
          {% endfor %}

        </div>
          <ul class="pagination" id="pagination" >
            <li class="page-item" ><a class="page-link " id="page-item" href="#">Previous</a></li>
            <li class="page-item"><a class="page-link" id="page" href="#">1</a></li>
            <li class="page-item"><a class="page-link" id="page" href="#">2</a></li>
            <li class="page-item"><a class="page-link" id="page" href="#">3</a></li>
            <li class="page-item"><a class="page-link" id="page-item" href="#">Next</a></li>
          </ul>
        
      </div>

    </div>
    <!-- End Portfolio Details -->

  </main><!-- End #main -->

  <div class="footer ">
    <div>
      <p>+989156557328 <span class="glyphicon glyphicon-earphone"></span></p>
      <p>mahdi.yazdanpanah000@gmail.com <span class="glyphicon glyphicon-globe"></span></p>
    </div>
    <div class="co ">
      <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">Email address</label>
        <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
      </div>
      <div class="mb-3">
        <label for="exampleFormControlTextarea1" class="form-label">Message</label>
        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
      </div>
      <button type="button" class="btn btn-success" id="liveToastBtn">send</button>

      <div class="toast-container position-fixed bottom-0 end-0 p-3">
        <div id="liveToast" class="toast" role="alert" aria-live="assertive" aria-atomic="true">
          <div class="toast-header">
            <img src="{% static '/img/favicon.png '%}" class="rounded me-2" alt="...">
            <strong class="me-auto">mahdi yazdanpanah</strong>
            <small>just now</small>
            <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
          </div>
          <div class="toast-body">
            Hello, your message has been sent successfully
            I will answer you as soon as I am online
          </div>
        </div>
      </div>


    </div>
  </div>
  </div>

  <!-- Vendor JS Files -->
  <script src="{% static '/vendor/purecounter/purecounter_vanilla.js '%}"></script>
  <script src="{% static '/vendor/bootstrap/js/bootstrap.bundle.min.js '%}"></script>
  <script src="{% static '/vendor/glightbox/js/glightbox.min.js '%}"></script>
  <script src="{% static '/vendor/isotope-layout/isotope.pkgd.min.js '%}"></script>
  <script src="{% static '/vendor/swiper/swiper-bundle.min.js '%}"></script>
  <script src="{% static '/vendor/waypoints/noframework.waypoints.js '%}"></script>
  <script src="{% static '/vendor/php-email-form/validate.js '%}"></script>

  <!-- Template Main JS File -->
  <script src="{% static '/js/main.js '%}"></script>

</body>
{% endblock %}

templates/blog/portfolio_details.html
{% extends './base.html' %}
{% load humanize %}
{% load static %}
{% load blog_tags %}
{% block content %}



  <!-- ======= Portfolio Details ======= -->
  <main id="main">
    <div>
      <div id="details">
        <div id="w">
          {% include 'blog/Widget.html' %}
          {% post_categories %}
          {% include 'blog/Widget2.html' %}
          {% latest_posts %}
        </div>
        <div class="container">
          <h1 id="title">blog detail</h1>

          {% for post in posts %}
          <div class="post container">
            <div class="media">
              <img width="100%" src="{{post.image.url}}" alt="">
            </div>
            <div class="title">
              <a href="{% url 'blog:single' pid=post.id %}"><h1>{{post.title}}</h1></a>
            </div>
            <div class="parent">
              <div class="info">
                <p><a href="{% url 'blog:author' author_username=post.author.username %}">{{post.author.get_full_name}}</a> <span class="glyphicon glyphicon-user"></span></p>
                <p>{{post.published_date |naturaltime}} <span class="glyphicon glyphicon-calendar"></span></p>
                <p>{{post.counted_views}} view <span class="glyphicon glyphicon-eye-open"></span></p>
                <p>
                  {% for cat in post.category.all %}
                  <a href="{% url 'blog:category' cat_name=cat.name %}">{{cat}}</a>{% if not forloop.last %},{% endif %}
                  {% endfor %}
                </p>
              </div>

              <div class="content">
                <p>{{post.content|truncatechars:150}}</p>
                <a href="{% url 'blog:single' pid=post.id %}" class="btn btn-Success active" aria-current="page">more</a>

              </div>
            </div>

          </div>
          {% endfor %}

        </div>
          <div class="pagin">
            {% if posts.has_previous %}
            <span class="page-item"><a  style="color: rgb(255, 255, 255);"  href="?page={{posts.previous_page_number}}">Previous</a></span>
            {% endif %}
            {% for i in posts.paginator.page_range %}
            {% if posts.number == i %}
            <span id="pager-link-active" ><a  style="color: rgb(255, 255, 255);"  href="?page={{i}}">{{i}}</a></span>
            {% else %}
            <span class="pager-links" ><a  style="color: rgb(255, 255, 255);" href="?page={{i}}">{{i}}</a></span>
            {% endif %}
            {% endfor %}
            {% if posts.has_next %}
            <span class="page-item"><a  style="color: rgb(255, 255, 255);" href="?page={{ posts.next_page_number }}">Next</a></span>
            {% endif %}
          </div>
        
      </div>

    </div>
    <!-- End Portfolio Details -->

  </main><!-- End #main -->

 
{% endblock %}

templates/blog/single.html
{% extends './base.html' %}
{% load static %}
{% load blog_tags %}
{% block content %}



<body>

  <!-- ======= Portfolio Details ======= -->
  <main id="main">
    <div>
      <div id="details">
        <div id="w">
          {% include 'blog/Widget.html' %}
          {% include 'blog/Widget1.html' %}
          {% include 'blog/Widget2.html' %}
          {% include 'blog/Widget4.html' %}
          {% latest_posts %}
        </div>
        <div class="container">
          <h1 id="title">{{posts.title}}</h1>


          <div class="post container">
            <div class="media">
              <img width="100%" src="{{posts.image.url}}" alt="">
            </div>
            <div class="title">
              <h1>{{posts.title}}</h1>
            </div>
            <div class="parent">
              <div class="info">
                <p>{{posts.author.get_full_name}} <span class="glyphicon glyphicon-user"></span></p>
                <p>{{posts.published_date | date:" D d M Y"}} <span class="glyphicon glyphicon-calendar"></span></p>
                <p>{{posts.counted_views}} view <span class="glyphicon glyphicon-eye-open"></span></p>
                <p>
                  {% for cat in posts.category.all %}
                  <a href="#">{{cat}}</a>{% if not forloop.last %},{% endif %}
                  {% endfor %}
                </p>
              </div>

              <div class="content">
                <p>{{posts.content|safe}}</p>

              </div>
            </div>
            <div>
              <div id="disqus_thread">
                <script>

                  var disqus_config = function () {
                    this.page.url = 'http://127.0.0.1:8000/blog/{{ posts.id }}';  // Replace PAGE_URL with your page's canonical URL variable
                    this.page.identifier = '{{ posts.id }}'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
                  };

                  (function () { // DON'T EDIT BELOW THIS LINE
                    var d = document, s = d.createElement('script');
                    s.src = 'https://127-0-0-1-8000-vy4qdgvbyj.disqus.com/embed.js';
                    s.setAttribute('data-timestamp', +new Date());
                    (d.head || d.body).appendChild(s);
                  })();
                </script>
                <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments
                    powered
                    by Disqus.</a></noscript>
              </div>
            </div>
          </div>

        </div>
      </div>

    </div>
    <!-- End Portfolio Details -->

  </main><!-- End #main -->


  {% endblock %}

templates/blog/widget1.html
{% load static %}
<div id="n">
    <p id="titel">category</p>
    <div id="Widget">
        <ul>
            {% for name,count in categories.items %}
            <li>
                <a id="category" href="{% url 'blog:category' cat_name=name %}">
                <p id="cat">{{name}}:</p>
                <p id="cat">{{count}}</p>
            </a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>

templates/blog/widget2.html
{% load static %}
<div id="n">
    <div class="card" aria-hidden="true">
        <img src="{% static 'img/ads.jpg' %}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title placeholder-glow">
                <span class="placeholder col-6"></span>
            </h5>
            <p class="card-text placeholder-glow">
                <span class="placeholder col-7"></span>
                <span class="placeholder col-4"></span>
                <span class="placeholder col-4"></span>
                <span class="placeholder col-6"></span>
                <span class="placeholder col-8"></span>
            </p>
            <a href="#" tabindex="-1" class="btn btn-primary disabled placeholder col-6"></a>
        </div>
    </div>

</div>

templates/blog/widget3.html
{% load humanize %}
{% load static %}

<p id="titel">latest posts</p>
<div id="n">
    {% for post in posts %}
    <div id="widget">
        <div id="item">
            <img id="itemimg" src="{{post.image.url}}" alt="">
            <a href="{% url 'blog:single' pid=post.id %}" id="pw"><p style="margin-bottom: 0px;">{{post.title|truncatechars:20}}</p></a>
            <h6 style="margin-bottom: 0px;">{{post.published_date | naturaltime}}</h6>
        </div>
    </div>
    {% endfor %}
</div>

templates/blog/widget4.html
{% load static %}

<p id="titel">tag clouds</p>
<div id="n" style="padding-top: 15px; padding-bottom: 15px; padding-left: 5px;">
    {% for tag in posts.tags.all %}
    <span id="tagbox"> <a  href="{% url 'blog:tag' tag_name=tag.name %}">{{tag.name}}</a></span>
    {% endfor %}


</div>